### ISSUE TITLE
Numina breaks sprint animation (No FOV change)

### ISSUE THREAD

**Issue by kmecpp** [lehjr/Numina#4]
This is the same issue I fixed this for 1.7.10: https://github.com/MachineMuse/Numina/pull/24

It was reverted here for some reason: https://github.com/MachineMuse/Numina/pull/26

Not sure why it was reverted because the change I made has been working totally fine for me for years. FOV looks normal both when not wearing power armor and with it with different upgrades.

Current code: https://github.com/lehjr/Numina/blob/1.16.5/src/main/java/com/github/lehjr/numina/util/client/event/FOVUpdateEventHandler.java

**Comment by lehjr** [comment]
"defeats the entire purpose of the FOV handler."

Sums it up. Simply restoring the effect to vanilla values does little when some find the effect nauseating to begin with. But since you're chiming in 3 years later, I'll add an option just for you.

**Comment by lehjr** [comment]
Will be available in the next release **with a config option**

**Comment by kmecpp** [comment]
If I remember correctly, without the FOV fix, the FOV changes dramatically (like 10x more than normal) when moving with power armor, which is indeed nausiating and ridiculous. I assumed that was the point of the FOV fix, not to disable the vanilla animation when you aren't even wearing power armor. Either way, a config option will work fine. Cheers.
